export const channelProcess = (id: string) => ({
  type: "ffmpeg",
  id: `restreamer-ui:ingest:${id}`,
  reference: id,
  input: [
    {
      id: "input_0",
      address: `{rtmp,name=${id}.stream}`,
      options: [
        "-fflags",
        "+genpts",
        "-thread_queue_size",
        "512",
        "-probesize",
        "5000000",
        "-analyzeduration",
        "3000000",
        "-rtmp_enhanced_codecs",
        "hvc1,av01,vp09",
      ],
    },
  ],
  output: [
    {
      id: "output_0",
      address: `{memfs}/${id}_{outputid}.m3u8`,
      options: [
        "-dn",
        "-sn",
        "-map",
        "0:1",
        "-codec:v",
        "copy",
        "-map",
        "0:0",
        "-codec:a",
        "copy",
        "-metadata",
        `title=${Bun.env.RESTREAMER_URL}/${id}/oembed.json`,
        "-metadata",
        "service_provider=datarhei-Restreamer",
        "-f",
        "hls",
        "-start_number",
        "0",
        "-hls_time",
        "2",
        "-hls_list_size",
        "6",
        "-hls_flags",
        "append_list+delete_segments+program_date_time+temp_file",
        "-hls_delete_threshold",
        "4",
        "-hls_segment_filename",
        `{memfs}/${id}_{outputid}_%04d.ts`,
        "-master_pl_name",
        `${id}.m3u8`,
        "-master_pl_publish_rate",
        "2",
        "-method",
        "PUT",
      ],
      cleanup: [
        {
          pattern: `memfs:/${id}**`,
          purge_on_delete: true,
        },
        {
          pattern: `memfs:/${id}_{outputid}.m3u8`,
          max_file_age_seconds: 24,
          purge_on_delete: true,
        },
        {
          pattern: `memfs:/${id}_{outputid}_**.ts`,
          max_files: 12,
          max_file_age_seconds: 24,
          purge_on_delete: true,
        },
        {
          pattern: `memfs:/${id}.m3u8`,
          max_file_age_seconds: 24,
          purge_on_delete: true,
        },
      ],
    },
  ],
  options: ["-loglevel", "level+info", "-err_detect", "ignore_err", "-y"],
  autostart: true,
  reconnect: true,
  reconnect_delay_seconds: 15,
  stale_timeout_seconds: 30,
  limits: {
    cpu_usage: 0,
    memory_mbytes: 0,
    waitfor_seconds: 5,
  },
});
